/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gym.management;
import javax.swing.*;
/**
 *
 * @author anand
 */
public class admindesktop extends javax.swing.JFrame {

    /** Creates new form admindesktop */
    public admindesktop() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        member = new javax.swing.JMenuItem();
        trainer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        viewmember = new javax.swing.JMenuItem();
        viewtrainer = new javax.swing.JMenuItem();
        payment = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        TAttendance = new javax.swing.JMenuItem();
        MAttendance = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1300, 768));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(204, 204, 255)));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1194, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 700, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon Gym Jframe/new member.png"))); // NOI18N
        jMenu1.setText("Add");

        member.setText("Add Member");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        jMenu1.add(member);

        trainer.setText("Add Trainer");
        trainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerActionPerformed(evt);
            }
        });
        jMenu1.add(trainer);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon Gym Jframe/update & delete member.png"))); // NOI18N
        jMenu2.setText("Update and Delete");

        viewmember.setText("View Member");
        viewmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewmemberActionPerformed(evt);
            }
        });
        jMenu2.add(viewmember);

        viewtrainer.setText("View Trainer");
        viewtrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtrainerActionPerformed(evt);
            }
        });
        jMenu2.add(viewtrainer);

        jMenuBar1.add(jMenu2);

        payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon Gym Jframe/payment.png"))); // NOI18N
        payment.setText("Payment");

        jMenuItem1.setText("payment");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        payment.add(jMenuItem1);

        jMenuBar1.add(payment);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon Gym Jframe/list of members.png"))); // NOI18N
        jMenu4.setText("Attendence");

        TAttendance.setText("Trainer Attendence");
        TAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAttendanceActionPerformed(evt);
            }
        });
        jMenu4.add(TAttendance);

        MAttendance.setText("Member Attendence");
        MAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAttendanceActionPerformed(evt);
            }
        });
        jMenu4.add(MAttendance);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon Gym Jframe/exit.png"))); // NOI18N
        jMenu5.setText("Exit");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu5.add(logout);

        close.setText("Close Application");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenu5.add(close);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO LOGOUT","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            new Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO CLOSE APPLICAION","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        new addmember().setVisible(true);
    }//GEN-LAST:event_memberActionPerformed

    private void trainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerActionPerformed
        new addtrainer().setVisible(true);
    }//GEN-LAST:event_trainerActionPerformed

    private void viewtrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewtrainerActionPerformed
        new viewtrainer().setVisible(true);
    }//GEN-LAST:event_viewtrainerActionPerformed

    private void viewmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewmemberActionPerformed
        new viewmember().setVisible(true);
    }//GEN-LAST:event_viewmemberActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new payment().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAttendanceActionPerformed
       new T_Attendance().setVisible(true);
    }//GEN-LAST:event_TAttendanceActionPerformed

    private void MAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAttendanceActionPerformed
        new M_Attendence().setVisible(true);
    }//GEN-LAST:event_MAttendanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindesktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MAttendance;
    private javax.swing.JMenuItem TAttendance;
    private javax.swing.JMenuItem close;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem member;
    private javax.swing.JMenu payment;
    private javax.swing.JMenuItem trainer;
    private javax.swing.JMenuItem viewmember;
    private javax.swing.JMenuItem viewtrainer;
    // End of variables declaration//GEN-END:variables

}
